spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - RewritePath=/api/(?<path>.*), /api/$\{path}

        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/api/books/**, /api/authors/**
          filters:
            - RewritePath=/api/(?<path>.*), /api/$\{path}

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/(?<path>.*), /api/$\{path}

        - id: parser-service
          uri: lb://parser-service
          predicates:
            - Path=/api/parsers/**
          filters:
            - RewritePath=/api/(?<path>.*), /api/$\{path}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
