server:
  port: 8888

spring:
  application:
    name: gateway-server


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1

        - id: bookcatalog-service
          uri: lb://bookcatalog-service
          predicates:
            - Path=/api/catalogs/**
          filters:
            - StripPrefix=1

        - id: author-service
          uri: lb://author-service
          predicates:
            - Path=/api/authors/**
          filters:
#            - RewritePath=/api/authors/(?<segment>.*), /$\{segment}
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
    com.shadow: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true